### ISSUE TITLE
Doesn't work on flutter 0.3.1

### ISSUE THREAD

**Issue by BPHvZ** [trentpiercy/flutter-candlesticks#1]
when running my app I get this:

The current Flutter SDK version is 0.3.1.

Because flutter_candlesticks 0.0.7 requires Flutter SDK version ^0.2.3 and no versions of
  flutter_candlesticks match >0.0.7 <0.1.0, flutter_candlesticks ^0.0.7 is forbidden.
So, because frypto depends on flutter_candlesticks ^0.0.7, version solving failed.
pub get failed (1)

**Comment by trentpiercy** [comment]
Should be fixed now :)

**Comment by BPHvZ** [comment]
It's working great again. Thanks for fixing it!
