### ISSUE TITLE
Function request

### ISSUE THREAD

**Issue by BPHvZ** [trentpiercy/flutter-candlesticks#2]
It would be awesome if the ticker/label (aka dollar sign) could be changed so that the chart could load data in other currencies without having the dollar sign as the price.

And selection callback would be amazing! like this: https://google.github.io/charts/flutter/example/interactions/selection_callback_example

These are just ideas to make this plugin even better

**Comment by trentpiercy** [comment]
Added a labelPrefix option. The selection stuff will be a lot more in depth. Feel free to try yourself and submit a PR. I might get to it in the future though just probably not any time soon.
