### ISSUE TITLE
Not work on flutter 0.7.5

### ISSUE THREAD

**Issue by lovestorymeetsvivalavida** [trentpiercy/flutter-candlesticks#5]
The current Dart SDK version is 2.1.0-dev.0.0.flutter-be6309690f.

Because depends on flutter_candlesticks >=0.0.2 which requires SDK version >=1.23.0 <=2.0.0, version solving failed.

**Comment by trentpiercy** [comment]
Set your dependency to `flutter_candlesticks: ^0.1.1`
